from __future__ import annotations

import inspect

import numpy as np
import pytest

torch = pytest.importorskip("torch")
# Keep PyTorch unit tests fast and deterministic on small CI machines.
torch.set_num_threads(1)

from fairvote.inference.mrp.rr_neural_mrp import RRNeuralMRPModel
from fairvote.privacy.mechanisms.kary_rr import privatize_many


def _simple_data(n: int = 160, *, seed: int = 123, epsilon: float = 1.5, k: int = 3):
    """Small synthetic RR dataset with a real demographic signal.

    True labels are created only inside the test fixture so that reported labels
    can be generated by the same k-ary RR mechanism used elsewhere in the
    project. The model under test receives only ``X`` and ``y_reported``.
    """

    rng = np.random.default_rng(seed)
    x0 = rng.integers(0, 2, size=n)
    x1 = rng.normal(size=n)
    X = np.column_stack([np.ones(n), x0, x1]).astype(float)

    true = np.where(x0 == 1, 0, 1)
    # Add a small third-class tail so k=3 is non-degenerate.
    tail = rng.random(n) < 0.08
    true = np.where(tail, 2, true).astype(int)

    y_reported = privatize_many(true, epsilon=epsilon, k=k, rng=rng)
    return X, true, y_reported


def _assert_probability_rows(p: np.ndarray, *, n: int, k: int) -> None:
    assert p.shape == (n, k)
    assert np.all(np.isfinite(p))
    assert np.all(p >= 0.0)
    assert np.allclose(p.sum(axis=1), 1.0, atol=1e-6)


def test_model_can_be_instantiated_with_configurable_neural_settings():
    model = RRNeuralMRPModel(
        k=3,
        epsilon=1.0,
        hidden_layers=(8, 4),
        dropout=0.2,
        weight_decay=1e-3,
        seed=42,
    )

    assert model.k == 3
    assert model.epsilon == 1.0
    assert model.hidden_layers == (8, 4)
    assert model.dropout == pytest.approx(0.2)
    assert model.weight_decay == pytest.approx(1e-3)
    assert not model.is_fitted
    assert model.A_np.shape == (3, 3)
    assert np.allclose(model.A_np.sum(axis=1), 1.0)


def test_fit_signature_uses_reported_not_true_labels():
    # Regression guard: the fit method should accept "y_reported" (privatised
    # labels) and must never expose a parameter named "y_true" or similar,
    # since the model must not train on unprivatised data.
    sig = inspect.signature(RRNeuralMRPModel.fit)
    assert "X" in sig.parameters
    assert "y_reported" in sig.parameters
    assert "y_true" not in sig.parameters
    assert "true_categories" not in sig.parameters
    assert "true" not in sig.parameters


def test_fit_runs_on_small_synthetic_dataset_without_crashing():
    X, _true, y_reported = _simple_data(n=80, seed=1)
    model = RRNeuralMRPModel(k=3, epsilon=1.5, hidden_layers=(6,), dropout=0.1, seed=7)

    info = model.fit(X, y_reported, steps=3, batch_size=32, lr=0.01)

    assert model.is_fitted
    assert info.steps == 3
    assert np.isfinite(info.final_loss)
    assert info.history is None


def test_predict_true_proba_shape_and_probability_normalisation():
    X, _true, y_reported = _simple_data(n=100, seed=2)
    model = RRNeuralMRPModel(k=3, epsilon=1.5, hidden_layers=(8, 4), dropout=0.1, seed=4)
    model.fit(X, y_reported, steps=5, batch_size=64, lr=0.01)

    p_true = model.predict_true_proba(X[:10])

    _assert_probability_rows(p_true, n=10, k=3)


def test_predict_reported_proba_shape_and_probability_normalisation():
    X, _true, y_reported = _simple_data(n=100, seed=3)
    model = RRNeuralMRPModel(k=3, epsilon=1.5, hidden_layers=(8,), dropout=0.0, seed=5)
    model.fit(X, y_reported, steps=5, batch_size=64, lr=0.01)

    p_reported = model.predict_reported_proba(X[:12])

    _assert_probability_rows(p_reported, n=12, k=3)


def test_poststratify_returns_valid_probability_vector_of_length_k():
    X, _true, y_reported = _simple_data(n=120, seed=8)
    model = RRNeuralMRPModel(k=3, epsilon=1.2, hidden_layers=(8,), seed=2)
    model.fit(X, y_reported, steps=5, batch_size=64, lr=0.01)

    weights = np.arange(1, 11, dtype=float)
    p = model.poststratify(X[:10], weights)

    assert p.shape == (3,)
    assert np.all(np.isfinite(p))
    assert np.all(p >= 0.0)
    assert np.isclose(p.sum(), 1.0, atol=1e-6)


def test_model_trains_using_reported_privatized_labels_not_true_labels():
    # Verify that training succeeds on privatised labels that genuinely differ
    # from the true labels.  If all labels happened to be unchanged by RR, the
    # test would not exercise the observation model meaningfully.
    X, true, y_reported = _simple_data(n=90, seed=9, epsilon=0.8)
    # Ensure the fixture actually privatised some labels.
    assert np.any(true != y_reported)

    model = RRNeuralMRPModel(k=3, epsilon=0.8, hidden_layers=(6,), seed=9)
    info = model.fit(X, y_reported, steps=4, batch_size=32, lr=0.01)

    assert model.is_fitted
    assert np.isfinite(info.final_loss)


def test_rr_transition_matrix_is_applied_in_reported_predictions_and_loss():
    X, _true, y_reported = _simple_data(n=70, seed=11, epsilon=1.1)
    model = RRNeuralMRPModel(k=3, epsilon=1.1, hidden_layers=(5,), dropout=0.0, weight_decay=0.0, seed=11)
    model.fit(X, y_reported, steps=3, batch_size=64, lr=0.01)

    X_eval = X[:15]
    y_eval = y_reported[:15]
    p_true = model.predict_true_proba(X_eval)
    p_reported = model.predict_reported_proba(X_eval)
    # The predicted reported distribution must be exactly theta @ A, i.e. the
    # latent true-category probabilities transformed by the RR channel matrix.
    expected_reported = p_true @ model.A_np

    assert np.allclose(p_reported, expected_reported, atol=1e-6)
    # With finite epsilon, the RR channel should generally move probabilities
    # away from the latent true distribution.
    assert not np.allclose(p_reported, p_true, atol=1e-4)

    manual_nll = -np.mean(np.log(np.clip(p_reported[np.arange(y_eval.size), y_eval], 1e-12, None)))
    assert model.loss(X_eval, y_eval) == pytest.approx(manual_nll, abs=1e-6)


def test_loss_can_decrease_on_simple_rr_problem():
    X, _true, y_reported = _simple_data(n=240, seed=5, epsilon=1.8)
    model = RRNeuralMRPModel(k=3, epsilon=1.8, hidden_layers=(10,), dropout=0.0, weight_decay=1e-4, seed=9)

    model.fit(X, y_reported, steps=1, batch_size=128, lr=0.01)
    before = model.loss(X, y_reported)
    model.fit(X, y_reported, steps=20, batch_size=128, lr=0.03)
    after = model.loss(X, y_reported)

    assert after < before


@pytest.mark.parametrize(
    "kwargs,exc_type,match",
    [
        ({"k": 1, "epsilon": 1.0}, ValueError, "k"),
        ({"k": 3, "epsilon": 0.0}, ValueError, "epsilon"),
        ({"k": 3, "epsilon": 1.0, "hidden_layers": (0,)}, ValueError, "hidden"),
        ({"k": 3, "epsilon": 1.0, "dropout": 1.0}, ValueError, "dropout"),
        ({"k": 3, "epsilon": 1.0, "weight_decay": -1.0}, ValueError, "weight_decay"),
    ],
)
def test_invalid_constructor_inputs_raise_clear_errors(kwargs, exc_type, match):
    with pytest.raises(exc_type, match=match):
        RRNeuralMRPModel(**kwargs)


@pytest.mark.parametrize(
    "bad_X,bad_y,match",
    [
        (np.ones(5), np.zeros(5, dtype=int), "2D"),
        (np.ones((5, 2)), np.zeros((5, 1), dtype=int), "1D"),
        (np.ones((5, 2)), np.array([0, 1, 2, 3, 0]), "labels"),
        (np.ones((5, 2)), np.array([0, 1, 2, 1]), "same number"),
        (np.array([[0.0, np.nan], [1.0, 2.0]]), np.array([0, 1]), "finite"),
        (np.ones((3, 2)), np.array([0.0, 1.5, 2.0]), "integer"),
    ],
)
def test_invalid_fit_inputs_are_rejected_with_clear_errors(bad_X, bad_y, match):
    model = RRNeuralMRPModel(k=3, epsilon=1.0, hidden_layers=(4,), seed=0)
    with pytest.raises(ValueError, match=match):
        model.fit(bad_X, bad_y, steps=2)


def test_prediction_before_fit_raises_clear_error():
    model = RRNeuralMRPModel(k=3, epsilon=1.0, hidden_layers=(4,), seed=0)
    with pytest.raises(RuntimeError, match="not fitted"):
        model.predict_true_proba(np.ones((2, 3)))
    with pytest.raises(RuntimeError, match="not fitted"):
        model.predict_reported_proba(np.ones((2, 3)))


def test_poststratify_rejects_invalid_weights_and_dimension_mismatch():
    X, _true, y_reported = _simple_data(n=80, seed=12)
    model = RRNeuralMRPModel(k=3, epsilon=1.5, hidden_layers=(6,), seed=12)
    model.fit(X, y_reported, steps=3, batch_size=32, lr=0.01)

    with pytest.raises(ValueError, match="1D"):
        model.poststratify(X[:3], np.ones((3, 1)))
    with pytest.raises(ValueError, match="same number"):
        model.poststratify(X[:3], np.ones(2))
    with pytest.raises(ValueError, match="non-negative"):
        model.poststratify(X[:3], np.array([1.0, -1.0, 1.0]))
    with pytest.raises(ValueError, match="positive sum"):
        model.poststratify(X[:3], np.zeros(3))


def test_predict_rejects_feature_dimension_mismatch_after_fit():
    X, _true, y_reported = _simple_data(n=80, seed=13)
    model = RRNeuralMRPModel(k=3, epsilon=1.5, hidden_layers=(6,), seed=13)
    model.fit(X, y_reported, steps=3, batch_size=32, lr=0.01)

    with pytest.raises(ValueError, match="columns"):
        model.predict_true_proba(np.ones((4, X.shape[1] + 1)))


def test_validation_history_and_early_stopping_are_recorded():
    X, _true, y_reported = _simple_data(n=120, seed=21, epsilon=1.2)
    model = RRNeuralMRPModel(k=3, epsilon=1.2, hidden_layers=(5,), dropout=0.0, seed=21)

    info = model.fit(
        X,
        y_reported,
        steps=30,
        batch_size=64,
        lr=0.01,
        validation_fraction=0.25,
        patience=1,
        min_delta=1e9,
    )

    assert info.early_stopped
    assert 1 <= info.steps < 30
    assert info.validation_loss is not None
    assert info.best_validation_loss is not None
    assert info.best_step is not None
    assert info.validation_history is not None
    assert len(info.validation_history) == info.steps
    assert info.runtime_sec >= 0.0


def test_explicit_validation_reported_label_nll_uses_reported_labels_only():
    X, _true, y_reported = _simple_data(n=100, seed=22, epsilon=1.4)
    model = RRNeuralMRPModel(k=3, epsilon=1.4, hidden_layers=(6,), seed=22)

    info = model.fit(
        X[:70],
        y_reported[:70],
        X_val=X[70:],
        y_val_reported=y_reported[70:],
        steps=5,
        batch_size=32,
        lr=0.01,
    )

    assert info.validation_loss == pytest.approx(model.reported_label_nll(X[70:], y_reported[70:]), abs=1e-7)
    assert info.validation_history is not None
    assert len(info.validation_history) == 5


def test_calibration_helpers_and_metadata_export(tmp_path):
    X, true, y_reported = _simple_data(n=120, seed=23, epsilon=1.6)
    checkpoint = tmp_path / "neural_mrp.pt"
    metadata = tmp_path / "neural_mrp.json"
    model = RRNeuralMRPModel(k=3, epsilon=1.6, hidden_layers=(6,), seed=23)
    info = model.fit(X, y_reported, steps=4, batch_size=64, lr=0.01, keep_history=True, checkpoint_path=checkpoint)

    summary = model.evaluation_summary(X, y_reported=y_reported, true_labels=true)
    assert summary["reported_label_nll"] == pytest.approx(model.reported_label_nll(X, y_reported), abs=1e-7)
    assert summary["brier_score"] == pytest.approx(model.brier_score(X, true), abs=1e-7)
    assert 0.0 <= summary["mean_normalized_entropy"] <= 1.0
    assert info.history is not None and len(info.history) == 4
    assert checkpoint.exists()

    exported = model.export_metadata(include_history=True)
    assert exported["observation_model"] == "reported_label_nll_through_kary_randomized_response"
    assert exported["fit_info"]["history"] is not None
    model.save_metadata(metadata, include_history=True)
    assert metadata.exists()
    assert "reported_label_nll" in exported["observation_model"]

    loaded = RRNeuralMRPModel.load_checkpoint(checkpoint)
    _assert_probability_rows(loaded.predict_true_proba(X[:5]), n=5, k=3)


def test_ensemble_multi_seed_predictions_are_valid():
    from fairvote.inference.mrp.rr_neural_mrp import fit_rr_neural_mrp_ensemble

    X, _true, y_reported = _simple_data(n=90, seed=24, epsilon=1.3)
    ensemble = fit_rr_neural_mrp_ensemble(
        X,
        y_reported,
        k=3,
        epsilon=1.3,
        seeds=[101, 102],
        model_kwargs={"hidden_layers": (4,)},
        fit_kwargs={"steps": 3, "batch_size": 32, "lr": 0.01},
    )

    p = ensemble.predict_true_proba(X[:7])
    _assert_probability_rows(p, n=7, k=3)
    std = ensemble.predict_true_proba_std(X[:7])
    assert std.shape == (7, 3)
    assert np.all(std >= 0.0)
    uncertainty = ensemble.uncertainty_summary(X[:7])
    assert uncertainty["max_seed_std"] >= uncertainty["mean_seed_std"] >= 0.0
