"""PyTorch RR-aware Neural MRP model.

The model in this module estimates latent true vote intention from features while
training only on privatized k-ary Randomized Response reports.

For respondent i with feature vector x_i, the neural network represents

    theta_i[t] = P_theta(true = t | x_i).

The training labels are not true votes. The observed label y_i is a privatized
report generated by the known Randomized Response channel

    A[t, r] = P_RR(reported = r | true = t).

The fitted likelihood is therefore

    P_theta(reported = y_i | x_i) = sum_t theta_i[t] * A[t, y_i].

This is the key privacy-aware observation model: optimisation is performed
against reported RR outputs only, while the network output remains a latent true
category distribution suitable for MRP/poststratification.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable, Optional, Sequence, Tuple, Union

import numpy as np

try:  # Keep the import error explicit for installations missing the ML dependency.
    import torch
    from torch import nn
except ModuleNotFoundError as exc:  # pragma: no cover - exercised only when torch is absent
    raise ModuleNotFoundError(
        'RRNeuralMRPModel requires PyTorch. Install with `pip install -e ".[dev,ai,streamlit,respondent]"` '
        "or another compatible torch installation before using "
        "fairvote.inference.mrp.rr_neural_mrp."
    ) from exc

from fairvote.inference.mrp.rr_mrp_fit import rr_transition_matrix


ArrayLike = Union[np.ndarray, Sequence[Sequence[float]]]


@dataclass(frozen=True)
class RRNeuralMRPFitInfo:
    """Summary returned by :meth:`RRNeuralMRPModel.fit`.

    Attributes
    ----------
    steps:
        Number of optimiser steps requested.
    final_loss:
        Full-data regularised RR-aware loss after fitting.
    history:
        Optional full-data loss history. Recorded only when ``keep_history=True``.
    """

    steps: int
    final_loss: float
    history: Optional[np.ndarray] = None


class _MLP(nn.Module):
    """Small configurable MLP that outputs unnormalised true-category logits."""

    def __init__(self, input_dim: int, output_dim: int, hidden_layers: Tuple[int, ...], dropout: float):
        super().__init__()
        layers: list[nn.Module] = []
        prev = int(input_dim)
        # Build hidden layers with ReLU activations and optional dropout.
        # An empty hidden_layers tuple yields a purely linear model.
        for width in hidden_layers:
            layers.append(nn.Linear(prev, int(width)))
            layers.append(nn.ReLU())
            if dropout > 0.0:
                layers.append(nn.Dropout(p=float(dropout)))
            prev = int(width)
        # Final linear layer maps to K unnormalised logits; softmax is applied
        # externally so the loss function can work with raw logits when needed.
        layers.append(nn.Linear(prev, int(output_dim)))
        self.net = nn.Sequential(*layers)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)


class RRNeuralMRPModel:
    """RR-aware neural MRP model trained on privatized reported answers.

    The network learns ``P_theta(true=t | x)`` from demographic/features ``X``.
    Because the true category is not observed, fitting uses the Randomized
    Response observation model

    ``P(reported=r | x) = sum_t P_theta(true=t | x) * A[t, r]``.

    Here ``A`` is the k-ary RR transition matrix reused from the existing MRP
    implementation. Training therefore uses only ``X`` and ``y_reported``; there
    is intentionally no API argument for true labels.

    Parameters
    ----------
    k:
        Number of categories/classes. Must be at least 2.
    epsilon:
        k-ary Randomized Response privacy parameter. Must be positive.
    hidden_layers:
        Widths of hidden layers. An empty sequence gives a linear softmax model;
        at least one positive width gives a genuine nonlinear neural model.
    dropout:
        Dropout probability applied after hidden activations during training.
    weight_decay:
        L2 penalty strength applied to trainable neural weights.
    seed:
        Seed for NumPy and PyTorch initialisation/batching.
    device:
        Torch device string. Defaults to CPU for reproducible lightweight runs.
    dtype:
        Torch floating dtype used internally.
    """

    def __init__(
        self,
        *,
        k: int,
        epsilon: float,
        hidden_layers: Sequence[int] = (32,),
        dropout: float = 0.0,
        weight_decay: float = 0.0,
        seed: int = 0,
        device: Union[str, torch.device] = "cpu",
        dtype: torch.dtype = torch.float32,
    ):
        self.k = self._validate_k(k)
        self.epsilon = self._validate_epsilon(epsilon)
        self.hidden_layers = self._validate_hidden_layers(hidden_layers)
        self.dropout = self._validate_dropout(dropout)
        self.weight_decay = self._validate_nonnegative_float(weight_decay, "weight_decay")
        self.seed = int(seed)
        self.device = torch.device(device)
        self.dtype = dtype

        # Fixed RR transition matrix. It is part of the likelihood, not a
        # trainable neural component.
        self.A_np = rr_transition_matrix(self.epsilon, self.k)
        self._network: Optional[_MLP] = None
        self._input_dim: Optional[int] = None
        self._last_fit_info: Optional[RRNeuralMRPFitInfo] = None

    @staticmethod
    def _validate_k(k: int) -> int:
        if not isinstance(k, (int, np.integer)):
            raise TypeError("k must be an integer")
        k = int(k)
        if k < 2:
            raise ValueError("k must be >= 2")
        return k

    @staticmethod
    def _validate_epsilon(epsilon: float) -> float:
        if not isinstance(epsilon, (int, float, np.floating)):
            raise TypeError("epsilon must be a number")
        eps = float(epsilon)
        if not np.isfinite(eps):
            raise ValueError("epsilon must be finite")
        if eps <= 0.0:
            raise ValueError("epsilon must be > 0")
        return eps

    @staticmethod
    def _validate_nonnegative_float(value: float, name: str) -> float:
        if not isinstance(value, (int, float, np.floating)):
            raise TypeError(f"{name} must be a number")
        out = float(value)
        if not np.isfinite(out):
            raise ValueError(f"{name} must be finite")
        if out < 0.0:
            raise ValueError(f"{name} must be >= 0")
        return out

    @staticmethod
    def _validate_dropout(dropout: float) -> float:
        out = RRNeuralMRPModel._validate_nonnegative_float(dropout, "dropout")
        if out >= 1.0:
            raise ValueError("dropout must be < 1")
        return out

    @staticmethod
    def _validate_hidden_layers(hidden_layers: Sequence[int]) -> Tuple[int, ...]:
        if isinstance(hidden_layers, (int, np.integer)):
            hidden_layers = (int(hidden_layers),)
        if hidden_layers is None:
            raise TypeError("hidden_layers must be a sequence of positive integers")
        widths = tuple(int(w) for w in hidden_layers)
        for w in widths:
            if w <= 0:
                raise ValueError("all hidden layer widths must be positive")
        return widths

    @staticmethod
    def _validate_steps(steps: int) -> int:
        if not isinstance(steps, (int, np.integer)):
            raise TypeError("steps must be an integer")
        steps = int(steps)
        if steps < 1:
            raise ValueError("steps must be >= 1")
        return steps

    @staticmethod
    def _validate_batch_size(batch_size: int) -> int:
        if not isinstance(batch_size, (int, np.integer)):
            raise TypeError("batch_size must be an integer")
        batch_size = int(batch_size)
        if batch_size < 1:
            raise ValueError("batch_size must be >= 1")
        return batch_size

    @staticmethod
    def _as_2d_float_array(X: ArrayLike, *, name: str = "X") -> np.ndarray:
        arr = np.asarray(X, dtype=np.float32)
        if arr.ndim != 2:
            raise ValueError(f"{name} must be a 2D array")
        if arr.shape[0] == 0:
            raise ValueError(f"{name} must have at least one row")
        if arr.shape[1] == 0:
            raise ValueError(f"{name} must have at least one column")
        if not np.all(np.isfinite(arr)):
            raise ValueError(f"{name} must contain only finite values")
        return arr

    def _as_y_reported(self, y_reported: Sequence[int], *, expected_n: Optional[int] = None) -> np.ndarray:
        # The API accepts reported RR categories only. A separate true-label
        # argument is intentionally absent so that training cannot accidentally
        # become supervised on unprivatized choices.
        raw = np.asarray(y_reported)
        if raw.ndim != 1:
            raise ValueError("y_reported must be a 1D array")
        if raw.size == 0:
            raise ValueError("y_reported must not be empty")
        if expected_n is not None and raw.size != int(expected_n):
            raise ValueError("X and y_reported must have the same number of rows")
        if not np.all(np.isfinite(raw.astype(float, copy=False))):
            raise ValueError("y_reported must contain only finite values")
        y = raw.astype(np.int64)
        if not np.all(raw == y):
            raise ValueError("y_reported must contain integer category labels")
        if np.any(y < 0) or np.any(y >= self.k):
            raise ValueError(f"y_reported labels must be in [0, {self.k - 1}]")
        return y

    def _set_seeds(self) -> None:
        # Fix all random sources for reproducibility across runs.
        np.random.seed(self.seed)
        torch.manual_seed(self.seed)
        if torch.cuda.is_available():  # pragma: no cover - CI normally runs on CPU
            torch.cuda.manual_seed_all(self.seed)

    def _build_network(self, input_dim: int) -> None:
        self._set_seeds()
        self._input_dim = int(input_dim)
        self._network = _MLP(
            input_dim=int(input_dim),
            output_dim=self.k,
            hidden_layers=self.hidden_layers,
            dropout=self.dropout,
        ).to(device=self.device, dtype=self.dtype)

    def _require_network(self) -> _MLP:
        if self._network is None:
            raise RuntimeError("Model is not fitted")
        return self._network

    def _check_input_dim(self, X: np.ndarray) -> None:
        if self._input_dim is not None and X.shape[1] != self._input_dim:
            raise ValueError(f"X has {X.shape[1]} columns, expected {self._input_dim}")

    def _to_tensor(self, X: np.ndarray) -> torch.Tensor:
        return torch.as_tensor(X, dtype=self.dtype, device=self.device)

    def _rr_matrix_tensor(self) -> torch.Tensor:
        return torch.as_tensor(self.A_np, dtype=self.dtype, device=self.device)

    def _true_proba_tensor(self, X_tensor: torch.Tensor) -> torch.Tensor:
        network = self._require_network()
        logits = network(X_tensor)
        return torch.softmax(logits, dim=1)

    def _reported_proba_tensor(self, X_tensor: torch.Tensor) -> torch.Tensor:
        # Convert latent true-category probabilities into probabilities for the
        # observed reported labels by applying the fixed RR channel matrix.
        theta = self._true_proba_tensor(X_tensor)
        return theta @ self._rr_matrix_tensor()

    def _weight_decay_penalty(self) -> torch.Tensor:
        # Sum of squared parameters, scaled by weight_decay / 2.  This is
        # equivalent to an L2 regularisation term in the loss.
        network = self._require_network()
        if self.weight_decay <= 0.0:
            return torch.zeros((), dtype=self.dtype, device=self.device)
        penalty = torch.zeros((), dtype=self.dtype, device=self.device)
        for param in network.parameters():
            penalty = penalty + torch.sum(param * param)
        return 0.5 * float(self.weight_decay) * penalty

    def _loss_tensor(self, X_tensor: torch.Tensor, y_tensor: torch.Tensor) -> torch.Tensor:
        # q is P(reported=r | x), not P(true=t | x). Indexing by y_tensor
        # therefore evaluates the likelihood of the privatized observed labels.
        q = self._reported_proba_tensor(X_tensor)
        q_y = q[torch.arange(q.shape[0], device=self.device), y_tensor]
        # Clamp only for numerical safety; it does not alter the RR observation
        # model except to avoid log(0) in finite-precision training.
        nll = -torch.mean(torch.log(torch.clamp(q_y, min=1e-12)))
        return nll + self._weight_decay_penalty()

    @property
    def is_fitted(self) -> bool:
        """Whether the underlying PyTorch network has been initialised/fitted."""

        return self._network is not None

    @property
    def last_fit_info(self) -> Optional[RRNeuralMRPFitInfo]:
        """Most recent fit summary, or ``None`` if the model has not been fitted."""

        return self._last_fit_info

    def fit(
        self,
        X: ArrayLike,
        y_reported: Sequence[int],
        *,
        lr: float = 1e-2,
        steps: int = 1000,
        batch_size: int = 512,
        keep_history: bool = False,
        verbose_every: int = 0,
    ) -> RRNeuralMRPFitInfo:
        """Fit the neural MRP model using privatized RR reports only.

        Parameters
        ----------
        X:
            Two-dimensional feature/design matrix. Rows are respondents and
            columns are demographic or encoded covariate features.
        y_reported:
            One-dimensional vector of observed privatized k-ary RR reports.
            These are the only training labels. True categories are neither
            required nor accepted by this API.
        lr:
            Adam learning rate.
        steps:
            Number of mini-batch optimisation steps.
        batch_size:
            Mini-batch size. Larger than ``n`` is allowed and becomes full-batch.
        keep_history:
            If true, record full-data regularised loss after each step.
        verbose_every:
            If positive, print the full-data loss every ``verbose_every`` steps.
        """

        X_arr = self._as_2d_float_array(X)
        y_arr = self._as_y_reported(y_reported, expected_n=X_arr.shape[0])
        lr = self._validate_nonnegative_float(lr, "lr")
        if lr <= 0.0:
            raise ValueError("lr must be > 0")
        steps = self._validate_steps(steps)
        batch_size = self._validate_batch_size(batch_size)
        if not isinstance(verbose_every, (int, np.integer)) or int(verbose_every) < 0:
            raise ValueError("verbose_every must be a non-negative integer")

        if self._network is None:
            self._build_network(X_arr.shape[1])
        else:
            self._check_input_dim(X_arr)

        network = self._require_network()
        network.train()
        self._set_seeds()

        # Cast the reported labels to long so PyTorch can index the loss tensor.
        X_tensor = self._to_tensor(X_arr)
        y_tensor = torch.as_tensor(y_arr, dtype=torch.long, device=self.device)
        # Adam is chosen for its adaptive learning rate, which suits the small
        # neural architectures and noisy RR training signals seen in practice.
        optimiser = torch.optim.Adam(network.parameters(), lr=float(lr))
        rng = np.random.default_rng(self.seed)
        n = X_arr.shape[0]
        hist: list[float] = []

        for step in range(1, steps + 1):
            # Mini-batches are sampled from the observed privatized dataset. The
            # fitted objective remains RR-aware for both full-batch and mini-batch
            # cases.
            if batch_size >= n:
                idx = np.arange(n)
            else:
                idx = rng.integers(0, n, size=batch_size)
            idx_tensor = torch.as_tensor(idx, dtype=torch.long, device=self.device)
            X_batch = X_tensor.index_select(0, idx_tensor)
            y_batch = y_tensor.index_select(0, idx_tensor)

            optimiser.zero_grad(set_to_none=True)
            batch_loss = self._loss_tensor(X_batch, y_batch)
            batch_loss.backward()
            optimiser.step()

            if keep_history or (verbose_every and step % int(verbose_every) == 0):
                full_loss = self.loss(X_arr, y_arr)
                if keep_history:
                    hist.append(full_loss)
                if verbose_every and step % int(verbose_every) == 0:
                    print(f"[RR-Neural-MRP] step={step} loss={full_loss:.6f}")

        # Evaluate full-data loss one final time after training concludes.
        # This is the regularised RR-aware NLL used for fit-quality reporting.
        final_loss = self.loss(X_arr, y_arr)
        info = RRNeuralMRPFitInfo(
            steps=steps,
            final_loss=float(final_loss),
            history=np.asarray(hist, dtype=float) if keep_history else None,
        )
        self._last_fit_info = info
        return info

    def loss(self, X: ArrayLike, y_reported: Sequence[int]) -> float:
        """Return full-data regularised RR-aware negative log-likelihood.

        The likelihood is evaluated on privatized ``y_reported`` labels via the
        RR channel matrix. It is not a supervised loss against true votes.
        """

        X_arr = self._as_2d_float_array(X)
        self._check_input_dim(X_arr)
        y_arr = self._as_y_reported(y_reported, expected_n=X_arr.shape[0])
        network = self._require_network()
        was_training = network.training
        network.eval()
        with torch.no_grad():
            X_tensor = self._to_tensor(X_arr)
            y_tensor = torch.as_tensor(y_arr, dtype=torch.long, device=self.device)
            out = float(self._loss_tensor(X_tensor, y_tensor).detach().cpu().item())
        if was_training:
            network.train()
        return out

    def predict_true_proba(self, X: ArrayLike) -> np.ndarray:
        """Predict latent true-category probabilities ``P_theta(true=t | x)``.

        Returns an ``(n, k)`` NumPy array whose rows are normalised probability
        vectors. These are latent estimates; they are not observed true votes.
        """

        X_arr = self._as_2d_float_array(X)
        self._check_input_dim(X_arr)
        network = self._require_network()
        was_training = network.training
        network.eval()
        with torch.no_grad():
            p = self._true_proba_tensor(self._to_tensor(X_arr)).detach().cpu().numpy()
        if was_training:
            network.train()
        return self._validate_probability_rows(p, name="predict_true_proba")

    def predict_reported_proba(self, X: ArrayLike) -> np.ndarray:
        """Predict reported-label probabilities after the RR observation channel.

        This returns ``P(reported=r | x) = sum_t P_theta(true=t | x) A[t, r]``.
        The rows are normalised because both the neural softmax output and the
        RR transition matrix are row-stochastic.
        """

        X_arr = self._as_2d_float_array(X)
        self._check_input_dim(X_arr)
        network = self._require_network()
        was_training = network.training
        network.eval()
        with torch.no_grad():
            q = self._reported_proba_tensor(self._to_tensor(X_arr)).detach().cpu().numpy()
        if was_training:
            network.train()
        return self._validate_probability_rows(q, name="predict_reported_proba")

    def poststratify(self, X_pop: ArrayLike, weights: Sequence[float]) -> np.ndarray:
        """Post-stratify latent true probabilities over population cells.

        ``X_pop`` should contain one row per population cell. ``weights`` are
        non-negative cell counts or proportions. They are normalised internally.
        The result is a length-``k`` estimated aggregate true vote distribution.
        """

        X_arr = self._as_2d_float_array(X_pop, name="X_pop")
        self._check_input_dim(X_arr)
        w = np.asarray(weights, dtype=float)
        if w.ndim != 1:
            raise ValueError("weights must be a 1D array")
        if w.size != X_arr.shape[0]:
            raise ValueError("X_pop and weights must have the same number of rows")
        if not np.all(np.isfinite(w)):
            raise ValueError("weights must contain only finite values")
        if np.any(w < 0.0):
            raise ValueError("weights must be non-negative")
        total = float(np.sum(w))
        if total <= 0.0:
            raise ValueError("weights must have positive sum")
        # Normalise population cell weights before averaging latent category
        # probabilities. This is the post-stratification step of MRP.
        w = w / total
        # Weighted sum of per-cell latent probabilities. The model's softmax
        # outputs stay probabilistic while the population weights determine
        # the aggregate mix.
        p = np.sum(self.predict_true_proba(X_arr) * w[:, None], axis=0)
        return self._validate_probability_vector(p, name="poststratify")

    @staticmethod
    def _validate_probability_rows(p: np.ndarray, *, name: str) -> np.ndarray:
        p = np.asarray(p, dtype=float)
        if p.ndim != 2:
            raise RuntimeError(f"{name} returned a non-2D array")
        if not np.all(np.isfinite(p)):
            raise RuntimeError(f"{name} returned non-finite probabilities")
        if np.any(p < -1e-7):
            raise RuntimeError(f"{name} returned negative probabilities")
        p = np.clip(p, 0.0, 1.0)
        row_sums = p.sum(axis=1, keepdims=True)
        if np.any(row_sums <= 0.0):
            raise RuntimeError(f"{name} returned a row with zero probability mass")
        p = p / row_sums
        if not np.allclose(p.sum(axis=1), 1.0, atol=1e-5):
            raise RuntimeError(f"{name} probabilities are not normalised")
        return p

    @staticmethod
    def _validate_probability_vector(p: np.ndarray, *, name: str) -> np.ndarray:
        p = np.asarray(p, dtype=float).reshape(-1)
        if not np.all(np.isfinite(p)):
            raise RuntimeError(f"{name} returned non-finite probabilities")
        if np.any(p < -1e-7):
            raise RuntimeError(f"{name} returned negative probabilities")
        p = np.clip(p, 0.0, 1.0)
        total = float(np.sum(p))
        if total <= 0.0:
            raise RuntimeError(f"{name} returned zero probability mass")
        p = p / total
        if not np.isclose(float(p.sum()), 1.0, atol=1e-6):
            raise RuntimeError(f"{name} probabilities are not normalised")
        return p


# Backwards-compatible aliases so older imports and the implementation plan
# wording continue to work without code changes.
NeuralRRMRPModel = RRNeuralMRPModel
NeuralRRMRPFitInfo = RRNeuralMRPFitInfo


__all__ = [
    "RRNeuralMRPFitInfo",
    "RRNeuralMRPModel",
    "NeuralRRMRPFitInfo",
    "NeuralRRMRPModel",
]
